var Icons = {
	//system and spells
	"party.png" : {block : 0, x : 0, y : 0},
	"ship.png" : {block : 0, x : 1, y : 0},
	"gold.png" : {block : 0, x : 2, y : 0},
	"banner.png" : {block : 0, x : 3, y : 0},
	"bannerLeft.png" : {block : 0, x : 4, y : 0},
	"bannerRight.png" : {block : 0, x : 5, y : 0},
	"noWeapon.png" : {block : 0, x : 6, y : 0},
	"noShield.png" : {block : 0, x : 7, y : 0},
	"noHat.png" : {block : 0, x : 8, y : 0},
	"noArmor.png" : {block : 0, x : 9, y : 0},
	"noBoots.png" : {block : 0, x : 10, y : 0},
	"noAmulet.png" : {block : 0, x : 11, y : 0},
	"chest.png" : {block : 0, x : 12, y : 0},
	"longSword.png" : {block : 0, x : 13, y : 0},
	"blank.png" : {block : 0, x : 14, y : 0},

	"selectView.png" : {block : 0, x : 0, y : 1},
	"selectViewLeft.png" : {block : 0, x : 1, y : 1},
	"selectViewTop.png" : {block : 0, x : 2, y : 1},
	"selectViewRight.png" : {block : 0, x : 3, y : 1},
	"selectViewBottom.png" : {block : 0, x : 4, y : 1},
	"selectActive.png" : {block : 0, x : 5, y : 1},
	"selectActiveLeft.png" : {block : 0, x : 6, y : 1},
	"selectActiveTop.png" : {block : 0, x : 7, y : 1},
	"selectActiveRight.png" : {block : 0, x : 8, y : 1},
	"selectActiveBottom.png" : {block : 0, x : 9, y : 1},
	"selectTarget.png" : {block : 0, x : 10, y : 1},
	"selectTargetLeft.png" : {block : 0, x : 11, y : 1},
	"selectTargetTop.png" : {block : 0, x : 12, y : 1},
	"selectTargetRight.png" : {block : 0, x : 13, y : 1},
	"selectTargetBottom.png" : {block : 0, x : 14, y : 1},
	
	"animHit.png" : {block : 0, x : 0, y : 2, frames : 4},
	"animPoison.png" : {block : 0, x : 4, y : 2, frames : 4},
	"animHitSpell.png" : {block : 0, x : 8, y : 2, frames : 4},
	"animSmoke.png" : {block : 0, x : 12, y : 2, frames : 3},

	"animMiss.png" : {block : 0, x : 0, y : 3, frames : 2},
	"animSpellCast.png" : {block : 0, x : 2, y : 3, frames : 3},
	"animResist.png" : {block : 0, x : 5, y : 3, frames : 2},
	"bag.png" : {block : 0, x : 7, y : 3},
	"animHotBall.png" : {block : 0, x : 8, y : 3, frames : 2},
	"animSlimeBall.png" : {block : 0, x : 10, y : 3},
	"animFireBall.png" : {block : 0, x : 11, y : 3, frames : 2},
	"animColdBallSmall.png" : {block : 0, x : 13, y : 3},
	"animHotBallSmall.png" : {block : 0, x : 14, y : 3},

	"animLightning.png" : {block : 0, x : 0, y : 4},
	"animBlackBallSmall.png" : {block : 0, x : 1, y : 4},
	"animRockSmall1.png" : {block : 0, x : 2, y : 4},

	//terrain
	"wall.png" : {block : 0, x : 0, y : 7},
	"floor.png" : {block : 0, x : 1, y : 7},
	"lava.png" : {block : 0, x : 2, y : 7},
	"volcano.png" : {block : 0, x : 3, y : 7},
	"grass.png" : {block : 0, x : 4, y : 7},
	"rubble.png" : {block : 0, x : 5, y : 7},
	"treeAlt.png" : {block : 0, x : 6, y : 7},
	"deadTree.png" : {block : 0, x : 7, y : 7},
	"stump.png" : {block : 0, x : 8, y : 7},
	"mountain.png" : {block : 0, x : 9, y : 7},
	"caveFloor.png" : {block : 0, x : 10, y : 7},
	"caveWall.png" : {block : 0, x : 11, y : 7},
	"deck.png" : {block : 0, x : 12, y : 7},
	"pool.png" : {block : 0, x : 13, y : 7},
	"columnTile.png" : {block : 0, x : 14, y : 7},

	"darkFloor.png" : {block : 0, x : 0, y : 8},
	"darkDoor.png" : {block : 0, x : 1, y : 8},
	"darkBridgeHorizontal.png" : {block : 0, x : 2, y : 8},
	"darkBridgeVertical.png" : {block : 0, x : 3, y : 8},
	"river.png" : {block : 0, x : 4, y : 8},
	"desert.png" : {block : 0, x : 5, y : 8},
	"bridgeHorizontal.png" : {block : 0, x : 6, y : 8},
	"bridgeVertical.png" : {block : 0, x : 7, y : 8},
	"doorInWall.png" : {block : 0, x : 8, y : 8},
	"dungeonGate.png" : {block : 0, x : 9, y : 8},
	"lockedDoor.png" : {block : 0, x : 10, y : 8},
	"palmTree.png" : {block : 0, x : 11, y : 8},
	"waterMountain.png" : {block : 0, x : 12, y : 8},
	"desertMountain.png" : {block : 0, x : 13, y : 8},
	"darkWall.png" : {block : 0, x : 14, y : 8},

	"knight.png" : {block : 1, x : 0, y : 0},
	"girlKnight.png" : {block : 1, x : 1, y : 0},
	"mercenary.png" : {block : 1, x : 2, y : 0},
	"ranger.png" : {block : 1, x : 3, y : 0},
	"girlArcher.png" : {block : 1, x : 4, y : 0},
	"assassin.png" : {block : 1, x : 5, y : 0},
	"wizard.png" : {block : 1, x : 6, y : 0},
	"girlWizard.png" : {block : 1, x : 7, y : 0},
	"necromancer.png" : {block : 1, x : 8, y : 0},

}
